title: Content
baseurl: ''
imageurl: 'http://hrmi-dataportal-content.unfolddata.com/assets/uploads'
siteurl: 'http://hrmi-dataportal-content.unfolddata.com'
permalink: /:categories/:title
markdown: kramdown
languages: &languages
  - name: 'English'
    value: 'en'
  - name: 'French'
    value: 'fr'
  - name: 'Spanish'
    value: 'es'
  - name: 'Portuguese'
    value: 'pt'
prose:
  media: "assets/uploads"
  rooturl: '_posts'
  siteurl: 'http://unfolddata.github.io/hrmi-dataportal-content/'
  relativeLinks: 'http://unfolddata.github.io/hrmi-dataportal-content/resources/links.jsonp'
  _posts:
    - name: "layout"
      field:
        element: "hidden"
        value: "default"
    - name: "permalink"
      field:
        element: "text"
        label: "Permalink"
        value: "/"
    - name: "lang"
      field:
        element: "select"
        label: "Select language"
        options: *languages
    - name: "title"
      field:
        element: "text"
        label: "Title"
        value: ""
