title: Content
baseurl: ''
imageurl: 'http://hrmi-dataportal-content.unfolddata.com/assets/uploads'
siteurl: 'http://hrmi-dataportal-content.unfolddata.com'
permalink: /:categories/:title
markdown: kramdown
languages: &languages
  - name: 'English'
    value: 'en'
  - name: 'French'
    value: 'fr'
prose:
  media: "assets/uploads"
  rooturl: '_posts'
  siteurl: 'http://unfolddata.github.io/hrmi-dataportal-content/'
  relativeLinks: 'http://unfolddata.github.io/hrmi-dataportal-content/resources/links.jsonp'
